name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -q sout_we_rouh.zip -d sout_we_rouh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get
        working-directory: sout_we_rouh

      - name: Build APK
        run: flutter build apk --release
        working-directory: sout_we_rouh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: sout_we_rouh/build/app/outputs/flutter-apk/app-release.apk
