name: Deploy Web
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: unzip -o sout_we_rouh.zip -d project_folder
      - uses: subosito/flutter-action@v2
        with: {flutter-version: '3.x'}
      - name: Build
        run: |
          cd project_folder
          flutter pub get
          flutter build web --release --base-href "/sout_we_rouh/"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project_folder/build/web
